icao_dict = {'EGHE': 'St Marys',
             'EGHC': 'Lands End',
             'EGHQ': 'Newquay',
             'EGTE': 'Exeter',
             'EGHH': 'Bournemouth',
             'EGHI': 'Southampton',
             'EGBJ': 'Gloucester',
             'EGSY': 'St Athan',
             'EGBB': 'Birmingham',
             'EGNX': 'East Midlands',
             'EGSH': 'Norwich',
             'EGNC': 'Carlisle',
             'EGCK': 'Caemarfon',
             'EGNH': 'Blackpool',
             'EGNO': 'Warton',
             'EGNR': 'Hawarden',
             'EGNV': 'Durham Teeside',
             'EGNJ': 'Humberside',
             'EGCC': 'Manchester_Ringway',
             'EGNT': 'Newcastle',
             'EGCN': 'Doncaster',
             'EGGP': 'Liverpool',
             'EGNM': 'Leeds Bradford',
             'EGPO': 'Stornoway',
             'EGPL': 'Benbecula',
             'EGPU': 'Tiree',
             'EGEO': 'Oban',
             'EGPB': 'Sumburgh',
             'EGPA': 'Kirkwall',
             'EGPC': 'Wick',
             'EGPE': 'Inverness',
             'EGPN': 'Dundee',
             'EGPI': 'Islay',
             'EGEC': 'Campbeltown',
             'EGPD': 'Aberdeen',
             'EGPH': 'Edinburgh',
             'EGPK': 'Prestwick',
             'EGPF': 'Glasgow',
             'EGMC': 'Southend',
             'EGLC': 'London City',
             'EGKB': 'Biggin Hill',
             'EGLF': 'Farnborough',
             'EGKA': 'Shoreham',
             'EGMD': 'Lydd',
             'EGSC': 'Cambridge',
             'EGTC': 'Cranfield',
             'EGTK': 'Oxford',
             'EGKK': 'Gatwick',
             'EGLL': 'Heathrow',
             'EGAE': 'Londonderry',
             'EGAC': 'Belfast City',
             'EGAA': 'Belfast International',
             'EGSS': 'Stansted',
             'EGFF': 'Cardiff',
             'EGGD': 'Bristol',
             'EGGW': 'Luton'
             }
